### ISSUE TITLE
KML not loading

### ISSUE THREAD

**Issue by Dwightski** [webaware/flexible-map#3]
Hi, I've been using your KML file short code for the WordPress site https://comprehensivetherapyapproach.com/directory/therapists/ where the 90 or so therapists are shown by location in a KML file for a while now. It stopped working recently, client couldn't tell me when.

API is functioning correctly and I am able to get the starting map in your docs, but KML with nothing but src and width has stopped working. I entered a center and zoom to get it to show a map, but kml information is not showing and map is acting funky and won't change location orientation.

I put together a sample kml to see if I was at limit, but the short one doesn't work either. Both kml files are attached, and I added a couple of images of the dev and widgets.

![kmltestfile](https://user-images.githubusercontent.com/32045620/57183877-acb8f480-6e67-11e9-83a4-9808d290cdcf.png)
![kmltestfile-2](https://user-images.githubusercontent.com/32045620/57183907-1933f380-6e68-11e9-8818-d440ddb41982.png)
[kmltester.zip](https://github.com/webaware/flexible-map/files/3144740/kmltester.zip)

**Comment by webaware** [comment]
It appears to be a hosting problem. If I take your kmltester.kml file and load it on DropBox, the map loads fine. But I can't load it from your site.

https://www.dropbox.com/s/a8g9qxyiwla1q3f/kmltester.kml?dl=1

It might be as simple as some security rules for the wp-admin folder on your server, so try making a `maps` folder in the root of the website and serving the maps from there.

If that fails, start checking your server logs for errors loading the kml files. You might need to speak with your host about your problems.

Or, if you can load the files elsewhere and serve them from there (even DropBox) then that might be your best solution.

cheers,
Ross

**Comment by Dwightski** [comment]
Thanks Ross, I appreciate you looking into it. I did some digging also, and
found now that we switched to https: (Last Friday) we need a community
allowable location to gain access.

It seems that the Map stopped working around the time you updated the KML
two months ago, and before we switched to https:. I'll keep working on it
and use your suggestion to make the map subdirectory and give it
permissions.
Thanks again for checking,

Dwight

**Comment by webaware** [comment]
It's not the HTTPS setup. I can load that map via curl via either HTTP or HTTPS, no problems. I can't get Google Maps JS to load it with either HTTP nor HTTPS.

Is there a reason your robots.txt is blocking all robots? I don't think it has an impact on Google Maps, but adding a maps folder and explicitly allowing it in robots.txt might help. At any rate, blocking all robots means all the useful search engines will be ignoring your website.

Do you have any nginx or Apache rules (.htaccess) that block bots? Check for anything blocking bots and spiders.

**Comment by webaware** [comment]
Woah! I just ran curl to see if that was the case, switching the user agent for one that Google search bot uses. I reckon you've been hacked. Google gets redirected to a defunct site that sounds like an escort service.

```
curl -iL https://comprehensivetherapyapproach.com/wp-admin/kmltester.kml -H "User-Agent: Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
HTTP/1.1 301 Moved Permanently
Server: nginx/1.14.1
Date: Tue, 07 May 2019 23:08:17 GMT
Content-Type: text/html; charset=iso-8859-1
Content-Length: 337
Connection: keep-alive
Location: http://eumamae.com/escort-tags/bakirkoy-escort/

curl: (7) Failed to connect to eumamae.com port 80: Connection refused
```

**Comment by Dwightski** [comment]
Yeah, I found that in the .htaccess file just now so someone has gotten
into her shared hosting account.
I deleted it, so it shouldn't happen again.

**Comment by webaware** [comment]
If you update the shortcode and append "?v=1" to the URL for the KML file, Google Maps will load that map now.

**Comment by Dwightski** [comment]
It is working again, the url fix in the .htaccess was the trick that was
leaving google out of the picture. The map works fine now.
Thank you for all your help on this.

**Comment by webaware** [comment]
No worries, glad you were able to get it sorted out quickly.

cheers,
Ross
